### ISSUE TITLE
EPGImportFilter does not work.

### ISSUE THREAD

**Issue by PD1LOI** [E2OpenPlugins/e2openplugin-EPGImportFilter#5]
If you use this plugin it will crash as soon as you click on "Advanced". You must create an empty setting.conf and put it in the plugin's directory. Furthermore, this plugin does not retrieve data, all in all nothing happens when you click Install, see photo.
![1_0_19_4C05_835_600_FFFF0000_0_0_0_20200324082858](https://user-images.githubusercontent.com/2943825/77399658-27ee0680-6daa-11ea-9d67-df3adcd01d87.jpg)

**Comment by PD1LOI** [comment]
Works whit the new version

**Comment by WanWizard** [comment]
What new version?

**Comment by PD1LOI** [comment]
Sorry Version 1.1 older version.
